# Generated by Django 4.0.6 on 2022-07-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_job_github_url_remove_job_heroku_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='JobSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=200, null=True)),
                ('field2', models.CharField(max_length=200, null=True)),
                ('field3', models.CharField(max_length=200, null=True)),
                ('field4', models.CharField(max_length=200, null=True)),
                ('field5', models.CharField(max_length=200, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.job')),
            ],
        ),
    ]
