# Generated by Django 4.0.6 on 2022-07-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_job_summary_job_city_job_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsummary',
            old_name='field1',
            new_name='task1',
        ),
        migrations.RenameField(
            model_name='jobsummary',
            old_name='field2',
            new_name='task2',
        ),
        migrations.RenameField(
            model_name='jobsummary',
            old_name='field3',
            new_name='task3',
        ),
        migrations.RenameField(
            model_name='jobsummary',
            old_name='field4',
            new_name='task4',
        ),
        migrations.RenameField(
            model_name='jobsummary',
            old_name='field5',
            new_name='task5',
        ),
    ]
