# Generated by Django 4.0.6 on 2022-07-21 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_field1_jobsummary_task1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
