# Generated by Django 4.0.6 on 2022-07-21 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_job_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
