# Generated by Django 4.0.6 on 2022-07-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_job_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsummary',
            old_name='task1',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='jobsummary',
            name='task2',
        ),
        migrations.RemoveField(
            model_name='jobsummary',
            name='task3',
        ),
        migrations.RemoveField(
            model_name='jobsummary',
            name='task4',
        ),
        migrations.RemoveField(
            model_name='jobsummary',
            name='task5',
        ),
    ]
