# Generated by Django 4.0.6 on 2022-07-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_job_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
