# Generated by Django 4.0.6 on 2022-07-25 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tech',
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.job')),
            ],
        ),
    ]
